name: Trigger API update

on:
  workflow_run:
  workflow_dispatch:

jobs:
  send_repo_dispatch_event:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.CONSUMER_ACCESS }}
          script: |
            const result = await github.rest.repos.createDispatchEvent({
              owner: 'sandeepnara777',
              repo: 'consumer',
              event_type: 'dev-deploy',
              client_payload: {}
            })
            console.log(result);
