name: ~ reusable workflow ops-tools export api info trigger
on:
  workflow_dispatch:
    inputs:
      RUNNER_LABEL:
        type: string
        default: "ubuntu-latest"

jobs:
  export-api-info:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          repository: sandeepnara777/consumer
          ref: main
          # ssh-key: ${{ secrets.CREDS_INFRA_GITHUB_REPOS_GHA_BEANS_PRIVATE_KEY }}
          path: consumer     
      - name: Trigger other repo workflow
        uses: WaleedAshraf/asyncapi-github-action@v0.0.10
        with:
          filepath: './consumer/.github/workflows/export_info.yml'

