name: Trigger API update

on:
  workflow_call:
    inputs:
      ENV:
        required: true
        type: string
      
  workflow_dispatch:
    inputs:
      ENV:
        required: true

jobs:
  send_repo_dispatch_event:
    runs-on: ubuntu-latest
    steps:
      - name: Check out consumer
        uses: actions/checkout@v2
        with:
          repository: sandeepnara777/consumer
          ref: main
          ssh-key: ${{ secrets.CONSUMER }}
          path: consumer
          persist-credentials: false

      - name: Invoke workflow with inputs
        uses: ./consumer/.github/actions
        with:
          STAGE: 'DEV'
