name: ~ reusable workflow ops-tools export api info trigger
on:
  workflow_dispatch:
    inputs:
      RUNNER_LABEL:
        type: string
        default: "ubuntu-latest"

jobs:
  export-api-info:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Invoke workflow in another repo with inputs
        uses: adityakar/workflow-dispatcher@v1.0    
        with:
          owner: sandeepnara777
          repo: consumer
          token: ${{ secrets.CONSUMER_ACCESS }}
          event_type: dev-deploy
          client_payload: '{}'
