name: ~ reusable workflow ops-tools export api info trigger
on:
  workflow_call:
    inputs:
      RUNNER_LABEL:
        type: string
        default: "ubuntu-latest"

jobs:
  export-api-info:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Trigger other repo workflow
        uses: WaleedAshraf/asyncapi-github-action@v0.0.10
        with:
          filepath: 'consumer/.github/workflows/export_info.yml'

