name: Trigger API update

on:
  workflow_call:
    inputs:
      STAGE:
        required: true
        type: string
      API:
        type: string
      REGION:
        required: true
        type: string
      
  workflow_dispatch:
    inputs:
      STAGE:
        required: true
      REGION:
        required: true

env:
  STAGE: ${{ inputs.STAGE }}
  REGION: ${{ inputs.REGION }}

jobs:
  send_repo_dispatch_event:
    runs-on: ubuntu-latest
    steps:
      - name: Check out nested ops-tools
        uses: actions/checkout@v3
        with:
          repository: sandeepnara777/consumer
          ref: main
          ssh-key: ${{ secrets.CONSUMER }}
          path: consumer

      - name: Invoke workflow with inputs
        uses: aurelien-baudet/workflow-dispatch@v2.1.1
        with:
          workflow: export_info.yml
          inputs: '{ "STAGE": "dev", "AWS_REGION": "us-east-2" }'
