name: Trigger API update

on:
  workflow_call:
    inputs:
      STAGE:
        required: true
        type: string
      API:
        type: string
      REGION:
        required: true
        type: string
      
  workflow_dispatch:
    inputs:
      STAGE:
        required: true
      REGION:
        required: true

env:
  STAGE: ${{ inputs.STAGE }}
  REGION: ${{ inputs.REGION }}

jobs:
  send_repo_dispatch_event:
    runs-on: ubuntu-latest
    steps:
      - name: Check out nested ops-tools
        uses: actions/checkout@v2
        with:
          repository: sandeepnara777/consumer
          ref: main
          ssh-key: ${{ secrets.CONSUMER }}
          path: consumer
          persist-credentials: false

      - name: Invoke workflow with inputs
        uses: ./consumer/.github/workflows/export_info.yml
        with:
          STAGE: ${{ inputs.STAGE }}
          AWS_REGION: ${{ inputs.REGION }}
