name: Trigger API update

on:
  workflow_call:
    inputs:
      ENV:
        required: true
        type: string
      
  workflow_dispatch:
    inputs:
      ENV:
        required: true

jobs:
  send_repo_dispatch_event:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check out consumer
        uses: actions/checkout@v3
        with:
          repository: sandeepnara777/consumer
          ref: main
          ssh-key: ${{ secrets.CONSUMER }}
          path: consumer
      - name: Invoke workflow with inputs
        id: output
        uses: ./producer_first/consumer/.github/actions/trigger
        with:
          STAGE: 'DEV'
      - run: echo "Simple step"
