name: Trigger API update

on:
  workflow_call:
    inputs:
      STAGE:
        required: true
        type: string
      API:
        type: string
      REGION:
        required: true
        type: string
      
  workflow_dispatch:
    inputs:
      STAGE:
        required: true
      REGION:
        required: true

env:
  STAGE: ${{ inputs.STAGE }}
  REGION: ${{ inputs.REGION }}

jobs:
  send_repo_dispatch_event:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6          
        with:
          github-token: ${{ secrets.CONSUMER_ACCESS }}
          script: |
            github.rest.repos.createDispatchEvent({
              owner: 'sandeepnara777',
              repo: 'consumer',
              event_type: 'dev-deploy',
              client_payload: { 'STAGE': ${{env.STAGE}},'AWS_REGION': ${{env.REGION}}
            })
